services:
  - type: web
    name: test_vocacional_metasistema
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    pythonVersion: 3.11.9
